---
title: POST /users Request Handling
---
classDiagram
    class UserController {
        <<Class>>
        -ICreateUserService _createUserService
        +UserController(ICreateUserService createUserService)
        +Create(string email, string username) User
    }
    class ICreateUserService {
        <<Interface>>
        +Call(CreateUserRequest createUserRequest) User
    }
    class CreateUserRequest {
        +string Email
        +string Username
        +Validate() bool
    }
    class CreateUserService {
        <<Class>>
        -UserModel _userModel
        -SendWelcomeEmailService _sendWelcomeEmailService
        -Kafka _kafka
        +CreateUserService(UserModel um, SendWelcomeEmailService es, Kafka k)
        +Call(CreateUserRequest createUserRequest) User
        -CheckActiveUsers(List~User~ users) bool
    }
    class UserModel {
        +FindUsersByEmail(string email) List~User~
        +CreateUser(string email, string username) User
    }
    class User {
        +int UserId
        +string Username
        +string Email

    }
    class SendWelcomeEmailService {
        +Call(string email, string username) bool
    }
    class Kafka {
        +PublishUserCreatedEvent(string email, string username) bool
    }
    UserController ..> ICreateUserService: depends on
    CreateUserService ..|> ICreateUserService: implements
    UserController ..> CreateUserRequest: depends on
    UserController ..> CreateUserService: depends on
    CreateUserService ..> UserModel: depends on
    UserModel ..> User: depends on
    CreateUserService ..> SendWelcomeEmailService: depends on
    CreateUserService ..> Kafka: depends on